### ISSUE TITLE
nightly restart fails with db error

### ISSUE THREAD

**Issue by BertrandHustle** [BertrandHustle/trebekbot#12]
Traceback (most recent call last):
  File "...main.py", line 183, in <module>
     champion_name = user_db.get_champion(user_db)[0]
  File "...db.py", line 109, in get_champion
     cursor = connection.cursor()
AttributeError: 'db' object has no attribute 'cursor'

**Comment by BertrandHustle** [comment]
Fixed; was calling the db itself:
user_db.get_champion(user_db)
instead of the connection:
user_db.get_champion(user_db.connection)
