### ISSUE TITLE
JSONDecodeError causing crashes

### ISSUE THREAD

**Issue by BertrandHustle** [BertrandHustle/trebekbot#18]
File "main.py", line 136, in <module>
    if host.hear(slack_output, 'whatis') and question_asked \
  File "/opt/app-root/src/host.py", line 68, in hear
    user = self.get_user(slack_output)
  File "/opt/app-root/src/host.py", line 118, in get_user
    user=user_id
  File "/opt/app-root/lib/python3.5/site-packages/slackclient/_client.py", line 83, in api_call
    result = json.loads(self.server.api_call(method, timeout=timeout, **kwargs))
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by BertrandHustle** [comment]
(None, None)
Traceback (most recent call last):
  File "main.py", line 138, in <module>
    current_answer = host.hear(slack_output, 'whatis')
  File "/opt/app-root/src/host.py", line 67, in hear
    channel = self.get_channel(slack_output)
  File "/opt/app-root/src/host.py", line 108, in get_channel
    channel = channel_id
  File "/opt/app-root/lib/python3.5/site-packages/slackclient/_client.py", line 83, in api_call
    result = json.loads(self.server.api_call(method, timeout=timeout, **kwargs))
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by BertrandHustle** [comment]
Fix this by recording the channel ID of trebekbot's first message and comparing that against channel IDs in subsequent command messages.  This eliminates the need to do an API call to check the channel name.
