### ISSUE TITLE
throws http error if /next is used without live question

### ISSUE THREAD

**Issue by BertrandHustle** [BertrandHustle/trebekbot#36]
[2020-06-01 15:28:16,746] ERROR in app: Exception on /next [POST]
2020-06-01T15:28:16.752855+00:00 app[web.1]: Traceback (most recent call last):
2020-06-01T15:28:16.752856+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/werkzeug/wrappers/base_response.py", line 298, in status_code
2020-06-01T15:28:16.752856+00:00 app[web.1]: self._status = "%d %s" % (code, HTTP_STATUS_CODES[code].upper())
2020-06-01T15:28:16.752857+00:00 app[web.1]: KeyError: <Response 0 bytes [200 OK]>
2020-06-01T15:28:16.752858+00:00 app[web.1]:
2020-06-01T15:28:16.752858+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-01T15:28:16.752859+00:00 app[web.1]:
2020-06-01T15:28:16.752859+00:00 app[web.1]: Traceback (most recent call last):
2020-06-01T15:28:16.752860+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
2020-06-01T15:28:16.752860+00:00 app[web.1]: response = self.full_dispatch_request()
2020-06-01T15:28:16.752862+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
2020-06-01T15:28:16.752862+00:00 app[web.1]: return self.finalize_request(rv)
2020-06-01T15:28:16.752862+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
2020-06-01T15:28:16.752863+00:00 app[web.1]: response = self.make_response(rv)
2020-06-01T15:28:16.752863+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 2139, in make_response
2020-06-01T15:28:16.752864+00:00 app[web.1]: rv.status_code = status
2020-06-01T15:28:16.752865+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/werkzeug/wrappers/base_response.py", line 300, in status_code
2020-06-01T15:28:16.752865+00:00 app[web.1]: self._status = "%d UNKNOWN" % code
2020-06-01T15:28:16.752866+00:00 app[web.1]: TypeError: %d format: a number is required, not Response

**Comment by BertrandHustle** [comment]
closing; outmoded by django migration
